ColorMode: true
X: "&a"
Y: "&b"
Z: "&c"
# color codes:
# §0 | black §1 | dark_blue §2 | dark_green §3 | dark_aqua §4 | dark_red §5 | dark_purple §6 | gold §7 | gray  §8 | dark_gray §9 | blue §a | green §b | aqua  §c | red §d | light_purple §e | yellow §f | white
# §g | minecoin_gold §h | material_quartz §i | material_iron §j | material_netherite §m | material_redstone §n | material_copper §p | material_gold §q | material_emerald §s | material_diamond §t | material_lapis §u | material_amethyst
# You are using PlayerCoords V1.2.5 
